apiVersion: v1
kind: Service
metadata:
  name: task-manager-svc
  labels:
    app: task-manager
spec:
  type: ClusterIP
  selector:
    app: task-manager
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP

